src/schema/resolvers.js
src/server.js

Copy of already-merged graphql PR to server side.

Add pending notifications logic

---

package-lock.json
package.json
src/constants.js
src/index.js
src/server.js
src/start_wallet.js
src/utils/emitterHelper.js
src/utils/utils.js

Error handling

---

src/schema/index.js
src/schema/resolvers.js

backend change for label-upcoming

Change for upcoming

---

package-lock.json
package.json
src/utils/logger.js

log rotate for 3 days

---

src/schema/resolvers.js

fix https://github.com/bodhiproject/bodhi-ui/issues/585

handle withdraw phase

---

src/api/test/address_manager.tests.js
src/api/test/base_contract.tests.js
src/api/test/bodhi_token.tests.js
src/api/test/oracle.tests.js
src/api/test/topic_event.tests.js
src/api/test/wallet.tests.js
src/server.js

merging for the release. fixes a bad import.

Fix import

---

src/config/index.js
src/schema/index.js
src/server.js
src/sync/index.js

allows to pass in flag `--passphrase=mypassword` to unlock the wallet at the server level. this is for dev purposes.

Enable wallet unlock + add peerNodeCount param 

---

src/graphql/queries.js
src/graphql/schema.js

added search topic, handle search insensitive

Search feature

---

package-lock.json
src/api/address-manager.js
src/api/blockchain.js
src/api/event-factory.js
src/api/qtum-utils.js
src/api/test/base-contract.tests.js
src/api/test/bodhi-token.tests.js
src/api/test/centralized-oracle.tests.js
src/api/test/decentralized-oracle.tests.js
src/api/test/mock/base-contract.js
src/api/test/mock/centralized-oracle.js
src/api/test/mock/decentralized-oracle.js
src/api/test/mock/event-factory.js
src/api/test/mock/oracle.js
src/api/test/mock/topic-event.js
src/api/test/topic-event.tests.js
src/api/test/wallet.tests.js
src/api/wallet.js
src/db/db-helper.js
src/graphql/mutations.js
src/graphql/queries.js
src/graphql/schema.js
src/models/centralized-oracle.js
src/models/topic.js
src/sync/index.js

hashId server change

---

src/graphql/queries.js
src/graphql/schema.js

fix search along with UI PR 956

fix search showing wrong phase

---

src/graphql/mutations.js
src/graphql/queries.js
src/graphql/schema.js

Server changes for: https://github.com/bodhiproject/bodhi-ui/pull/992/files

Reset approve

---

src/route/graphql.js

change graphql cursor to block

---

src/graphql/queries.js
src/graphql/schema.js
src/route/graphql.js

add mostvoted

---

src/graphql/queries/transactions.js

merging this one-liner. confirmed fix.

Remove array from tx filters

---

src/api/multiple-results-event.js
src/graphql/queries/bets.js
src/graphql/queries/biggest-winners.js
src/graphql/queries/events.js
src/graphql/queries/index.js
src/graphql/queries/most-bets.js
src/graphql/queries/result-sets.js
src/graphql/queries/search-events.js
src/graphql/queries/total-result-bets.js
src/graphql/queries/transactions.js
src/graphql/queries/utils.js
src/graphql/queries/withdrawable-events.js
src/graphql/queries/withdraws.js
src/graphql/schema.js
src/models/bet.js
src/models/multiple-results-event.js
src/models/result-set.js
src/models/tx-receipt.js
src/models/withdraw.js
src/utils/index.js

180 total result bets

---

src/graphql/queries/total-result-bets.js
src/graphql/schema.js

Change for getting:
totalBets,
betterBets,
totalVotes,
betterVotes,
then will use them to do 
implement the withdraw table

Change total result bets

---

package-lock.json
src/graphql/queries/events.js
src/graphql/queries/search-events.js
src/graphql/queries/withdrawable-events.js
src/graphql/resolvers.js
src/graphql/schema.js
test/graphql/schema-helper.js

Used to show last round result, totalbets[resultIndex] and userbets[resultIndex]

Add previous round bets

---

test/graphql/mutations.tests.js
test/graphql/schema-helper.js

Only have tests for `add-pending-event` now, if it looks good, I will keep working on the rest.

Graphql test

---

src/config/index.js
src/sync/index.js
src/web3.js
test/sync/parsers/multiple-results-event.tests.js

Temporarily disabling websockets until I can find a better solution or until web3 gets fixed.

Disable websockets

---

src/sync/bet-placed.js
src/sync/blocks.js
src/sync/multiple-results-event-created.js
src/sync/result-set.js
src/sync/vote-placed.js
src/sync/vote-result-set.js
src/sync/winnings-withdrawn.js

#269 
@BernardHan Please take a look at the changes I made when using the `pLimit` module. This pertains to your PR. Also FYI, I asked in the pLimit repo to see if we need to pass functions as well when creating a limit func (not sure about it).

269 plimit refs

---

CHANGELOG.md
docker/mainnet/docker-compose.yml
docker/testnet/docker-compose.yml
src/index.js

Will handle the regression tests in a later PR.

Better err handling

---

CHANGELOG.md
src/sync/index.js

#278 
Tests will be included in the full sync tests.

278 remove start block file
